#Set the input config files

#Data configs:
variables_file : 'configs/Data_variables.txt'
samples_file : 'configs/Data_samples.txt'
json_output : 'configs/Data_samples.json'
feather_path : "/data/at3/scratch3/jharrison/nominal_feather"
nominal_path : "/data/at3/scratch3/jharrison/nominal"


region_name : 'CR_1Z_0b_2SFOS_data_newvars'
cut_choice : 'cut_1Z_0b_2SFOS'


#Cut expressions:
cut_0Z_0b_2SFOS: '(total_charge==0) & (nTaus_OR==0) & (nJets_OR_DL1r_77==0) & (lep_Pt_0*1e-3>25) & (lep_Pt_1*1e-3>25) & (lep_Pt_2*1e-3>25) & (lep_Pt_3*1e-3>25) & (lep_isolationFCLoose_0) & (lep_isolationFCLoose_1) & (lep_isolationFCLoose_2) & (lep_isolationFCLoose_3) & ( ((lep_ID_0!=-lep_ID_1)|(abs(Mll01-91.2e3)>10e3)) & ((lep_ID_0!=-lep_ID_2)|(abs(Mll02-91.2e3)>10e3)) & ((lep_ID_0!=-lep_ID_3)|(abs(Mll03-91.2e3)>10e3)) & ((lep_ID_1!=-lep_ID_2)|(abs(Mll12-91.2e3)>10e3)) & ((lep_ID_1!=-lep_ID_3)|(abs(Mll13-91.2e3)>10e3)) & ((lep_ID_2!=-lep_ID_3)|(abs(Mll23-91.2e3)>10e3)) ) & ( ((lep_ID_0==-lep_ID_1)&(lep_ID_2==-lep_ID_3)) | ((lep_ID_0==-lep_ID_2)&(lep_ID_1==-lep_ID_3)) | ((lep_ID_0==-lep_ID_3)&(lep_ID_1==-lep_ID_2)) )'

cut_1Z_0b_2SFOS : '(total_charge==0) & (nTaus_OR==0) & (nJets_OR_DL1r_77==0)  & (lep_Pt_0*1e-3>25) & (lep_Pt_1*1e-3>25) & (lep_Pt_2*1e-3>25) & (lep_Pt_3*1e-3>25) & (lep_isolationFCLoose_0) & (lep_isolationFCLoose_1) & (lep_isolationFCLoose_2) & (lep_isolationFCLoose_3) & ((lep_ID_0==-lep_ID_1)&(abs(Mll01-91.2e3)<10e3)&((lep_ID_2!=lep_ID_3) | (abs(Mll23-91.2e3)>10e3)) | (lep_ID_0==-lep_ID_2)&(abs(Mll02-91.2e3)<10e3)&((lep_ID_1!=lep_ID_3) | (abs(Mll13-91.2e3)>10e3)) |(lep_ID_0==-lep_ID_3)&(abs(Mll03-91.2e3)<10e3)&((lep_ID_1!=lep_ID_2) | (abs(Mll12-91.2e3)>10e3)) |(lep_ID_1==-lep_ID_2)&(abs(Mll12-91.2e3)<10e3)&((lep_ID_0!=lep_ID_3) | (abs(Mll03-91.2e3)>10e3)) |(lep_ID_1==-lep_ID_3)&(abs(Mll13-91.2e3)<10e3)&((lep_ID_0!=lep_ID_2) | (abs(Mll02-91.2e3)>10e3)) |(lep_ID_2==-lep_ID_3)&(abs(Mll23-91.2e3)<10e3)&((lep_ID_0!=lep_ID_1) | (abs(Mll01-91.2e3)>10e3))) & ( (((lep_ID_0==-lep_ID_1)&(lep_ID_2==-lep_ID_3))) | (((lep_ID_0==-lep_ID_2)&(lep_ID_1==-lep_ID_3))) | (((lep_ID_0==-lep_ID_3)&(lep_ID_1==-lep_ID_2))) )'

cut_2Z_0b: '( ((lep_ID_0==-lep_ID_1) & (abs(Mll01-91.2e3)<10e3) & (lep_ID_2==-lep_ID_3) & (abs(Mll23-91.2e3)<10e3)) | ((lep_ID_0==-lep_ID_2) & (abs(Mll02-91.2e3)<10e3) & (lep_ID_1==-lep_ID_3) & (abs(Mll13-91.2e3)<10e3)) | ((lep_ID_0==-lep_ID_3) & (abs(Mll03-91.2e3)<10e3) & (lep_ID_1==-lep_ID_2) & (abs(Mll12-91.2e3)<10e3)) )'


cut_1Z_0b_0SFOS : ''

cut_1Z_0b_1SFOS : '(total_charge==0) & (nTaus_OR==0) & (nJets_OR_DL1r_77==0)  & (lep_Pt_0*1e-3>25) & (lep_Pt_1*1e-3>25) & (lep_Pt_2*1e-3>25) & (lep_Pt_3*1e-3>25) & (lep_isolationFCLoose_0) & (lep_isolationFCLoose_1) & (lep_isolationFCLoose_2) & (lep_isolationFCLoose_3) & ((lep_ID_0==-lep_ID_1)&(abs(Mll01-91.2e3)<10e3)) & ((lep_ID_2!=-lep_ID_3)|(abs(Mll23-91.2e3)>10e3)) | (lep_ID_0==-lep_ID_2)&(abs(Mll02-91.2e3)<10e3)) & ((lep_ID_1!=-lep_ID_3)|(abs(Mll13-91.2e3)>10e3)) | (lep_ID_0==-lep_ID_3)&(abs(Mll03-91.2e3)<10e3)) & ((lep_ID_1!=-lep_ID_2)|(abs(Mll12-91.2e3)>10e3)) | (lep_ID_1==-lep_ID_2)&(abs(Mll12-91.2e3)<10e3)) & ((lep_ID_0!=-lep_ID_3)|(abs(Mll03-91.2e3)>10e3)) | (lep_ID_1==-lep_ID_3)&(abs(Mll13-91.2e3)<10e3)) & ((lep_ID_0!=-lep_ID_2)|(abs(Mll02-91.2e3)>10e3)) | (lep_ID_2==-lep_ID_3)&(abs(Mll23-91.2e3)<10e3)) & ((lep_ID_0!=-lep_ID_1)|(abs(Mll01-91.2e3)>10e3)) ) & ( ((lep_ID_0==-lep_ID_1)&(lep_ID_2!=-lep_ID_3)) | ((lep_ID_0==-lep_ID_2)&(lep_ID_1!=-lep_ID_3)) | ((lep_ID_0==-lep_ID_3)&(lep_ID_1!=-lep_ID_2)) | ((lep_ID_1==-lep_ID_2)&(lep_ID_0!=-lep_ID_3)) | ((lep_ID_1==-lep_ID_3)&(lep_ID_0!=-lep_ID_2)) | ((lep_ID_2==-lep_ID_3)&(lep_ID_0!=-lep_ID_1)))'









############################################################################################################################
############################################################################################################################
############################################################################################################################


#Useful:
XXX_4lep_PT : '(lep_Pt_0*1e-3>25) & (lep_Pt_1*1e-3>25) & (lep_Pt_2*1e-3>25) & (lep_Pt_3*1e-3>25) &'
XXX_4lep_ISO : '(lep_isolationFCLoose_0) & (lep_isolationFCLoose_1) & (lep_isolationFCLoose_2) & (lep_isolationFCLoose_3) &'

XXX_1_SFOS: '( ((lep_ID_0==-lep_ID_1)&(lep_ID_2!=-lep_ID_3)) | ((lep_ID_0==-lep_ID_2)&(lep_ID_1!=-lep_ID_3)) | ((lep_ID_0==-lep_ID_3)&(lep_ID_1!=-lep_ID_2)) | ((lep_ID_1==-lep_ID_2)&(lep_ID_0!=-lep_ID_3)) | ((lep_ID_1==-lep_ID_3)&(lep_ID_0!=-lep_ID_2)) | ((lep_ID_2==-lep_ID_3)&(lep_ID_0!=-lep_ID_1)))'

XXX_2_SFOS: '( ((lep_ID_0==-lep_ID_1)&(lep_ID_2==-lep_ID_3)) | ((lep_ID_0==-lep_ID_2)&(lep_ID_1==-lep_ID_3)) | ((lep_ID_0==-lep_ID_3)&(lep_ID_1==-lep_ID_2)) )'

XXX_0_Z: '( ((lep_ID_0!=-lep_ID_1)|(abs(Mll01-91.2e3)>10e3)) & ((lep_ID_0!=-lep_ID_2)|(abs(Mll02-91.2e3)>10e3)) & ((lep_ID_0!=-lep_ID_3)|(abs(Mll03-91.2e3)>10e3)) & ((lep_ID_1!=-lep_ID_2)|(abs(Mll12-91.2e3)>10e3)) & ((lep_ID_1!=-lep_ID_3)|(abs(Mll13-91.2e3)>10e3)) & ((lep_ID_2!=-lep_ID_3)|(abs(Mll23-91.2e3)>10e3)) )'

XXX_1_Z: '((lep_ID_0==-lep_ID_1)&(abs(Mll01-91.2e3)<10e3)) & ((lep_ID_2!=-lep_ID_3)|(abs(Mll23-91.2e3)>10e3)) | (lep_ID_0==-lep_ID_2)&(abs(Mll02-91.2e3)<10e3)) & ((lep_ID_1!=-lep_ID_3)|(abs(Mll13-91.2e3)>10e3)) | (lep_ID_0==-lep_ID_3)&(abs(Mll03-91.2e3)<10e3)) & ((lep_ID_1!=-lep_ID_2)|(abs(Mll12-91.2e3)>10e3)) | (lep_ID_1==-lep_ID_2)&(abs(Mll12-91.2e3)<10e3)) & ((lep_ID_0!=-lep_ID_3)|(abs(Mll03-91.2e3)>10e3)) | (lep_ID_1==-lep_ID_3)&(abs(Mll13-91.2e3)<10e3)) & ((lep_ID_0!=-lep_ID_2)|(abs(Mll02-91.2e3)>10e3)) | (lep_ID_2==-lep_ID_3)&(abs(Mll23-91.2e3)<10e3)) & ((lep_ID_0!=-lep_ID_1)|(abs(Mll01-91.2e3)>10e3)) )'

XXX_2_Z: '( ((lep_ID_0==-lep_ID_1) & (abs(Mll01-91.2e3)<10e3) & (lep_ID_2==-lep_ID_3) & (abs(Mll23-91.2e3)<10e3)) | ((lep_ID_0==-lep_ID_2) & (abs(Mll02-91.2e3)<10e3) & (lep_ID_1==-lep_ID_3) & (abs(Mll13-91.2e3)<10e3)) | ((lep_ID_0==-lep_ID_3) & (abs(Mll03-91.2e3)<10e3) & (lep_ID_1==-lep_ID_2) & (abs(Mll12-91.2e3)<10e3)) )'

