#Set the input config files

#Bkg configs:
variables_file : 'configs/Bkg_variables.txt'
samples_file : 'configs/Bkg_samples.txt'
json_output : 'configs/Bkg_samples.json'
feather_path : "/data/at3/scratch3/jharrison/nominal_feather"
nominal_path : "/data/at3/scratch3/jharrison/nominal"
region_name : 'CR_1Z_0b_2SFOS_newvars'

#VLL configs:
#variables_file: 'configs/VLL_variables.txt'
#samples_file : 'configs/VLL_samples.txt'
#json_output : 'configs/VLL_samples.json'
#feather_path : "/data/at3/scratch3/jharrison/nominal_feather"
#nominal_path : "/data/at3/scratch3/jharrison/VLL/"
#region_name : 'CR_1Z_0b_2SFOS_VLLs_newvars'
#region_name : 'test_region'

cut_choice : 'cut_1Z_0b_2SFOS'

#Cut expressions:
cut_1Z_0b_2SFOS : '(total_charge==0) & (nTaus_OR==0) & (nJets_OR_DL1r_77==0)  & (lep_Pt_0*1e-3>25) & (lep_Pt_1*1e-3>25) & (lep_Pt_2*1e-3>25) & (lep_Pt_3*1e-3>25) & (lep_isolationFCLoose_0) & (lep_isolationFCLoose_1) & (lep_isolationFCLoose_2) & (lep_isolationFCLoose_3) & ((lep_ID_0==-lep_ID_1)&(abs(Mll01-91.2e3)<10e3)&((lep_ID_2!=lep_ID_3) | (abs(Mll23-91.2e3)>10e3)) | (lep_ID_0==-lep_ID_2)&(abs(Mll02-91.2e3)<10e3)&((lep_ID_1!=lep_ID_3) | (abs(Mll13-91.2e3)>10e3)) |(lep_ID_0==-lep_ID_3)&(abs(Mll03-91.2e3)<10e3)&((lep_ID_1!=lep_ID_2) | (abs(Mll12-91.2e3)>10e3)) |(lep_ID_1==-lep_ID_2)&(abs(Mll12-91.2e3)<10e3)&((lep_ID_0!=lep_ID_3) | (abs(Mll03-91.2e3)>10e3)) |(lep_ID_1==-lep_ID_3)&(abs(Mll13-91.2e3)<10e3)&((lep_ID_0!=lep_ID_2) | (abs(Mll02-91.2e3)>10e3)) |(lep_ID_2==-lep_ID_3)&(abs(Mll23-91.2e3)<10e3)&((lep_ID_0!=lep_ID_1) | (abs(Mll01-91.2e3)>10e3))) & ( (((lep_ID_0==-lep_ID_1)&(lep_ID_2==-lep_ID_3))) | (((lep_ID_0==-lep_ID_2)&(lep_ID_1==-lep_ID_3))) | (((lep_ID_0==-lep_ID_3)&(lep_ID_1==-lep_ID_2))) )'