samples_path : '/data/at3/scratch3/jharrison/nominal_feather/Regions'
feather_file : 'CR_1Z_0b_2SFOS_data_newvars.ftr'
signal_file : 'CR_1Z_0b_2SFOS_data_newvars.ftr'

#Ntuple output settings
add_to_ntuple: True
base_dir: '/data/at3/scratch3/jharrison/nominal/data'
out_dir: '/data/at3/scratch3/jharrison/mod_ntuples_newvars/data'

vll_base_dir: '/data/at3/scratch3/jharrison/VLL'
vll_out_dir: '/data/at3/scratch3/jharrison/mod_VLL'

#Set training variables
training_variables:     ['met_met',
#    'met_phi',
    'Mllll0123',
    'HT_lep',
    'HT_jets',
    'nJets_OR',
#    'sumPsbtag',
    'weight',
    'sample',
    'eventNumber',
#    'Mll01',
#    'Mll02',
#    'Mll03',
#    'Mll12',
#    'Mll13',
#    'Mll23',
    'best_mZll',
    'other_mZll',
    'M3l_high',
    'M3l_low',
    'best_ptZll',
    'other_ptZll'
]

#Set training hyperparameters
Train : True
train_size: -1
model_type : 'VAE'
batch_size : 1024
learning_rate : 0.0005
num_epochs : 30
load_path : 'outputs/VAE_1943-16-08-2022/model_state_dict.pt'
test_dump : False
use_eventnumber: True
even_or_odd : 'Even'

#Preprocessing settings
remove_zero_weights : True
remove_negative_weights : True
weight_loss : True
added_weight_factor : 500

#Test settings
validation_groups : ['VV', 'Top', 'VH', 'VVV']
validation_fraction : 0.2
test_fraction : 0.2
val_frequency : 2
num_test_samples : -1
evaluate_signals : True


#Set chosen samples
chosen_samples: ['data']
 
#Set the groupings
groupings:
   data: 'data'
