#Set the input config files
region: '0Z_0b_mLEQe'
region_save_name : '0Z_0b_mLEQe_10GeV_NewVars'

#Bkg configs:
use_default: True
variables_file : 'Bkg_variables.txt'
samples_file : 'Bkg_samples.txt'
json_output : 'Bkg_samples.json'
nominal_path : "/data/at3/scratch3/multilepton/VLL_production/nominal"
feather_path : "/data/at3/scratch3/multilepton/VLL_production/feather/5lep"

#Data configs:
#variables_file : 'configs/Data_variables.txt'
#samples_file : 'configs/Data_samples.txt'
#json_output : 'configs/Data_samples.json'
#feather_path : "/data/at3/scratch3/jharrison/nominal_feather/Regions/CR_0Z_0b_2SFOS"
#nominal_path : "/data/at3/scratch3/jharrison/nominal/data"
#nominal_path : "/data/at3/scratch3/multilepton/newvars/data"

#VLL configs:
#variables_file: 'configs/variable_choices/VLL_variables.txt'
#samples_file : 'configs/sample_choices/VLL_samples.txt'
#json_output : 'configs/sample_jsons/VLL_samples.json'
#feather_path : "/data/at3/scratch3/jharrison/nominal_feather/Regions/CR_1Z_0b_2SFOS"
#nominal_path : "/data/at3/scratch3/jharrison/VLL/"
#region_name : 'CR_0Z_0b_2SFOS_VLLs_newstring'
#region_name : 'test_region'


cut_choice : 'cut_0Z_0b_mLEQe'
variable_functions_choice: 'no_funcs'

0Z_0b_0SFOS_funcs: ['find_bestZll_pair', 'calc_4lep_pTll', 'calc_m3l', 'make_jets_continuous', 'get_MTLepLepMET']
0Z_0b_1SFOS_funcs: ['find_Z_pairs_0Z_1SFOS', 'calc_4lep_pTll', 'calc_m3l', 'make_jets_continuous', 'get_MTLepLepMET']
0Z_0b_2SFOS_funcs: ['find_pairings_0Z_2SFOS', 'calc_4lep_pTll', 'calc_m3l', 'make_jets_continuous', 'get_MTLepLepMET']
1Z_0b_1SFOS_funcs: ['find_Z_pairs_1Z_1SFOS', 'calc_4lep_pTll', 'calc_m3l', 'make_jets_continuous', 'get_MTLepLepMET']
1Z_0b_2SFOS_funcs: ['find_Z_pairs_1Z', 'calc_4lep_pTll', 'calc_m3l', 'make_jets_continuous', 'get_MTLepLepMET']
2Z_0b_funcs: ['find_Z_pairs_2Z', 'calc_4lep_pTll', 'calc_m3l', 'make_jets_continuous', 'get_MTLepLepMET']

no_funcs: []

cut_0Z_0b_mLEQe: '((fivelep_type==4)|(fivelep_type==5)|(fivelep_type==6)|(sixlep_type==4)|(sixlep_type==5)|(sixlep_type==6)|(sixlep_type==7)|(abs(lep_ID_1)*multilepornone_type>0))&(num_Zee_best+num_Zmm_best==0)&(nTaus_OR==0)&(lep_Pt_0*1e-3>10)&(lep_Pt_1*1e-3>10)&(lep_Pt_2*1e-3>10)&(lep_Pt_3*1e-3>10)&(lep_Pt_4*1e-3>10) & (lep_isolationFCLoose_0)&(lep_isolationFCLoose_1)&(lep_isolationFCLoose_2)&(lep_isolationFCLoose_3)& (lep_isolationFCLoose_4)&(nJets_OR_DL1r_77==0)'

#-----------------------------------------------------------------------------------------------------

 