#Set the input config files
region: '2lSS'
region_save_name : '2lSS'

#Bkg configs:
use_default: True
variables_file : 'Bkg_variables.txt'
#variables_file : 'Bkg_variables_2LSS.txt'
samples_file : 'Bkg_samples.txt'
json_output : 'Bkg_samples.json'
nominal_path : "/data/at3/common/multilepton/FinalSystProduction/nominal"
feather_path : "/data/at3/common/multilepton/FinalSystProduction/feather/Regions"



cut_choice : 'cut_2lSS'
variable_functions_choice: 'no_funcs'



no_funcs: []
cut_2lSS: '(custTrigMatch_LooseID_FCLooseIso_SLT)&(dilep_type>0)&(abs(total_charge)==2) & (lep_Pt_0*1e-3>10) & (lep_Pt_1*1e-3>10)'

cut_2lSS_Alejandro: '(custTrigMatch_LooseID_FCLooseIso_SLT)&(dilep_type>0)&(abs(total_charge)==2) & (lep_Pt_0*1e-3>20) & (lep_Pt_1*1e-3>20) & (nJets_OR>=2) & ((lep_ID_0*lep_ID_1)>0) & (nJets_OR_DL1r_77>=1) & (passPLIVVeryTight_0) & (passPLIVVeryTight_1) & '


#(abs(self.data['lep_ID_0'])==11) & (self.data['lep_isTightLH_0']==1) & (self.data['lep_chargeIDBDTLoose_0']==1) & (self.data['lep_ambiguityType_0']==0) & (self.data['lep_DFCommonAddAmbiguity_0']<=0))|((abs(self.data['lep_ID_0'])==13) & (self.data['lep_isMedium_0'])==1) too...
#-----------------------------------------------------------------------------------------------------

 